org.gradle.caching=true
org.gradle.parallel=true
javaVersion=21
kotlinVersion=2.2.21
kotlinGradlePluginVariant=gradle813
libgdxVersion=1.14.0
junitPlatformVersion=1.10.0
junitVersion=5.10.0
jacocoVersion=0.8.12
lwjglVersion=3.3.3
gdxJnigenLoaderVersion=2.5.2
jlayerVersion=1.0.1-gdx
jorbisVersion=0.0.17
asmVersion=9.7
opentest4jVersion=1.3.0
apiguardianVersion=1.1.2
gsonVersion=2.11.0
kotlinxCoroutinesVersion=1.8.0
errorProneAnnotationsVersion=2.27.0
jetbrainsAnnotationsVersion=23.0.0
kotlinxCoroutinesKotlinStdlibVersion=1.9.21
kotlinStdlibAnnotationsVersion=13.0
kotlinReflectVersion=1.6.10
snakeyamlVersion=2.6
group=com.ktome
version=0.1.0-SNAPSHOT
