package com.ktome.game.loot

enum class MilestoneRewardRejectionReason {
    UNKNOWN_BASE,
    NON_EQUIPMENT_REWARD,
    FORBIDDEN_BASE,
    DROP_FLOOR_MISMATCH,
    SPECIAL_TEMPLATE_SOURCE_TIER_MISMATCH,
    SPECIAL_TEMPLATE_ZONE_MISMATCH,
    PROFESSION_MISMATCH,
    NO_USABLE_MATERIAL,
    AFFIX_INFEASIBLE,
    RESERVED_SLOT,
    OCCUPIED_SLOT_REQUIRES_REPLACEMENT,
}
